#include "codex/persistent_settings.h"

extern "C" __declspec(dllimport) void __stdcall ExitProcess(unsigned long code);

namespace { unsigned long failures = 0; void require(bool value) { failures += value ? 0UL : 1UL; } }

extern "C" void mainCRTStartup() {
  using namespace codex;
  PersistentSettings settings = make_default_settings();
  require(settings.schema_version == kSettingsSchemaVersion);
  require(settings.ble_slot == 1);
  require(settings.sound_enabled);
  require(settings.sound_volume == 100);
  require(settings.display_brightness == 80);
  require(settings.animation_strength == 100);
  require(settings.standby_timeout_seconds == 180);
  require(settings.super_standby_timeout_seconds == 7200);
  require(settings.power_button_mode == PowerButtonMode::ConnectedStandby);
  require(settings.auto_ultra_timeout_seconds == 0);
  require(!settings.ultra_touch_wake);
  require(settings.joystick_sensitivity_percent == 100);
  require(!settings.anti_accidental_shutdown);
  require(settings.protocol_profile == ProtocolProfile::Auto);
  require(!settings.layer_routing_enabled);
  require(settings.configured_layer_count == 6);
  require(settings.layer1_command_app_targets[0] == 0);
  require(settings.higher_codex_masks[0][0] == 0);
  require(settings.bluetooth_enabled);
  require(settings.keycap_ids[3][0] == 'C');
  require(settings.keycap_ids[3][7] == 'R');
  require(settings.crc32 == settings_crc32(settings));
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings.layer = 7;
  require(validate_settings(settings) == SettingsLoadResult::InvalidCrc);
  settings = make_default_settings();
  settings.schema_version = 99;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidSchema);
  settings = make_default_settings();
  settings.ble_slot = 4;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.sound_volume = 55;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.display_brightness = 5;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.transport = TransportMode::Mixed;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings.super_standby_timeout_seconds = 7200;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings.super_standby_timeout_seconds = 18000;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings.super_standby_timeout_seconds = 4000;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.auto_ultra_timeout_seconds = 10800;
  settings.power_button_mode = PowerButtonMode::UltraStandby;
  settings.ultra_touch_wake = true;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings.auto_ultra_timeout_seconds = 7200;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.power_button_mode = static_cast<PowerButtonMode>(2);
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.joystick_sensitivity_percent = 45;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.joystick_sensitivity_percent = 150;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings = make_default_settings();
  settings.joystick_sensitivity_percent = 205;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.bluetooth_enabled = false;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings = make_default_settings();
  settings.protocol_profile = static_cast<ProtocolProfile>(9);
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.configured_layer_count = 3;
  settings.layer_routing_enabled = true;
  settings.layer1_command_app_targets[5] = kLayer1CommandOverrideTarget;
  settings.higher_codex_masks[4][3] = 0x3F;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings.layer1_command_app_targets[5] = 6;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::Valid);
  settings.configured_layer_count = 1;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.layer1_command_app_targets[0] = 1;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  settings = make_default_settings();
  settings.higher_codex_masks[0][0] = 0x40;
  settings.crc32 = settings_crc32(settings);
  require(validate_settings(settings) == SettingsLoadResult::InvalidValue);
  ExitProcess(failures);
}
